version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server_a
      - server_b
  server_a:
    build: ./server-a
    ports:
      - "3001:3000"
    volumes:
      - ./server-a:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: node app.js
  server_b:
    build: ./server-b
    ports:
      - "3002:3000"
    volumes:
      - ./server-b:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: node app.js
  k6:
    image: grafana/k6
    volumes:
      - ./k6:/scripts
    entrypoint: ["k6", "run", "/scripts/test-script.js"]
    depends_on:
      - nginx 